# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SAKit_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
#请求框架
  pod 'Alamofire', '~> 5.2'

  #指示器
  pod 'SVProgressHUD'
  
  pod 'YYKit'
  #约束框架
  pod 'SnapKit', '~> 5.0.0'
  
  #键盘管理
  pod 'IQKeyboardManagerSwift', '6.3.0'
  
  #键值模型转换
  pod 'HandyJSON'
  
  #轮播
  pod 'LLCycleScrollView'
  
  #刷新控件
  pod 'MJRefresh'

end
